### ISSUE TITLE
The ability to only create a single client instead of both at the same time

### ISSUE THREAD

**Issue by wolfderechter** [NiceNode/nice-node#132]
Problem description
-
The ability to only create a single client instead of both at the same time.

For NiceNode developers
-
{
  "platform": "win32",
  "platformRelease": "10.0.19045",
  "arch": "x64",
  "totalMemory": 17106214912,
  "niceNodeVersion": "2.2.0-alpha"
}

**Comment by jgresham** [comment]
one work-around for now is to create both nodes, then for the node you want to remove, select it, go to settings and Remove Node at the bottom of settings.

**Comment by jgresham** [comment]
can be done with a work-around and not on our roadmap for now
