### ISSUE TITLE
Style scroll bars (dark mode) [CSS & React]

### ISSUE THREAD

**Issue by jgresham** [NiceNode/nice-node#133]
## Feature details

Scroll bars do not automatically get themed 

- [ ] Scroll bars should match the dark mode styling

<img width="995" alt="Captura de Pantalla 2022-12-02 a la(s) 4 49 38 p m" src="https://user-images.githubusercontent.com/3721291/205414150-ff30b46d-2240-4323-b6e6-c38df5ab8ce0.png">

Something similar to Chrome's dark mode would look good. In our case, the background could match the same background as everything else.
<img width="219" alt="Captura de Pantalla 2022-12-02 a la(s) 4 57 38 p m" src="https://user-images.githubusercontent.com/3721291/205414564-4cd761c6-10b1-4e92-b598-cdf2b174c5ee.png">

Suggested by @wolfderechter

**Comment by rthe1** [comment]
Hi I'd like to be assigned to this!

**Comment by jgresham** [comment]
done
