### ISSUE TITLE
Default nethermind install fails to start. 

### ISSUE THREAD

**Issue by bitstr3am** [NiceNode/nice-node#147]
Problem description. 
-

Walked through default install, chose nethermind. Start fails. Services.msc shows docker service is running tho.

Here is relevant logs section:

{
  killed: false,
  code: 1,
  signal: null,
  cmd: 'docker  pull nethermind/nethermind',
  stdout: 'Using default tag: latest\n',
  stderr: 'error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/images/create?fromImage=nethermind%2Fnethermind&tag=latest": open //./pipe/docker_engine: The system cannot find the file specified.\n',
  innerError: Error: Command failed: docker  pull nethermind/nethermind
  error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/images/create?fromImage=nethermind%2Fnethermind&tag=latest": open //./pipe/docker_engine: The system cannot find the file specified.
  
      at ChildProcess.exithandler (node:child_process:406:12)
      at ChildProcess.emit (node:events:394:28)
      at ChildProcess.emit (node:domain:475:12)
      at maybeClose (node:internal/child_process:1064:16)
      at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
      at Process.callbackTrampoline (node:internal/async_hooks:130:17) {
    killed: false,
    code: 1,
    signal: null,
    cmd: 'docker  pull nethermind/nethermind'
  },
  level: 'error',
  service: 'nice-node-service',
  timestamp: '2022-12-17T07:06:11.992Z'
}

For NiceNode developers
-
{
  "platform": "win32",
  "platformRelease": "10.0.19045",
  "arch": "x64",
  "totalMemory": 17087881216,
  "niceNodeVersion": "1.5.1-alpha"
}

**Comment by jgresham** [comment]
@bitstr3am Docker Desktop needs to be running in the background for NiceNode to work. In newer versions of NiceNode, NiceNode will automatically inform the user if Docker stops and auto-start Docker given permission from the user.
