### ISSUE TITLE
Fuzzy log search 

### ISSUE THREAD

**Issue by jgresham** [NiceNode/nice-node#152]
## Feature details

Right now the log search filter is an exact match. Use an npm package to accomplish this or implement your own algoritm. Shouldn't impact performance too much. Include the runtime of the fuzzy search.

- [ ] Ignore case - A search for "error" should return logs with "... Error ... "
- [ ] Char off-by-one - a search for "eror" should return logs with " ... error ... "

Current line of code with the exact match `log.includes(searchTerm)` at https://github.com/jgresham/nice-node/blob/f01558eb32e622a48b3aa1b8493357e646aa9a93/src/renderer/Generics/redesign/LogMessage/Logs.tsx#L105

**Comment by leeoniya** [comment]
shameless plug: https://github.com/leeoniya/uFuzzy#a-biased-appraisal-of-similar-work
