### ISSUE TITLE
Add node modal is laggy/buggy

### ISSUE THREAD

**Issue by jgresham** [NiceNode/nice-node#345]
## Problem details

On slightly slower machines, the add node modal is laggy and buggy.

It is slow to load
Node icons load slowly
Node requirements don't always show up or even load

**Comment by jgresham** [comment]
Should we close this @corn-potage?

**Comment by corn-potage** [comment]
Hmm it's technically solved with the initial render of AddNode, but I still see some lag on the Requirements screen (at least now it's more obvious to the user with the spinning icon). I'm hoping that it'll be completely gone with the BenchBuddy implementation 🤔 so it's up to you I think!

**Comment by jgresham** [comment]
Sounds good, I think a loading spinner is very acceptable!
