### ISSUE TITLE
Rebrand Speedometer as BenchBuddy

### ISSUE THREAD

**Issue by jgresham** [NiceNode/nice-node#380]
## Feature details

https://speedometer.tools/ and https://github.com/NiceNode/speedometer should be BenchBuddy and 

![BenchBuddy](https://github.com/NiceNode/nice-node/assets/3721291/d8a2d496-6d7b-4193-a268-49b53d1e7a2d)

**Comment by jgresham** [comment]
new repo https://github.com/NiceNode/bench-buddy-website

**Comment by jgresham** [comment]
This is mostly done, just finishing touches and awaiting final commands/output. Great work @Gathin23 !

**Comment by Gathin23** [comment]
Thank you @jgresham
