### ISSUE TITLE
Following Development Steps to Start App Throws Errors

### ISSUE THREAD

**Issue by keyneom** [NiceNode/nice-node#390]
## Problem details

What went wrong and what should have happened?

I'm trying to run the application from a git clone of the repository by following the steps outlined in the README (I wanted to help contribute the the project if possible). After cloning the repo I created a `.env` file with the values indicated in the README. I then ran `npm install`  and `npm start` from the repo's root directory.

When I view the app in the browser I receive the following errors:

![image](https://github.com/NiceNode/nice-node/assets/1523791/93232597-3518-4508-b75e-20c27f49717e)

![image](https://github.com/NiceNode/nice-node/assets/1523791/9a3234bb-7077-4df0-a94c-ee14be8b189e)

I am attempting to build and run the application in a podman container running on an Ubuntu 22 host. There is plenty of storage and RAM available.

**Comment by jgresham** [comment]
Please take a look at the readme. Just need to define some vars in .env file
![image](https://github.com/NiceNode/nice-node/assets/3721291/3b1ea0a5-7bc5-4e52-9dce-a18da6f1f074)

**Comment by keyneom** [comment]
As I indicated, I believe I've already created the `.env` file with the appropriate values. Unless, I need a fake token value that follows a specific format.

![image](https://github.com/NiceNode/nice-node/assets/1523791/44baa5b9-41c7-4acf-9b4e-aca17604d627)

**Comment by jgresham** [comment]
Oh ok, sorry. I'll check when I'm home.

**Comment by jgresham** [comment]
Hmm, I haven't seen this issue before. What version of node and npm are you using? `node -v` `npm -v`

**Comment by jgresham** [comment]
Oh, I see the issue now... you were trying to open it in a browser. 

After running `npm start` the app should open locally. Afaik, you can't use a separate browser or window. You'll need some way to connect to the display of your remote Ubuntu 22 machine. 

I'll add a note in the readme that an app window will open after `npm start` so that others don't try this.

**Comment by keyneom** [comment]
I see, as I mentioned I'm running the application within a podman container on an Ubuntu host. I'll see what I can do to access the application opening locally.

**Comment by keyneom** [comment]
I was able to get things running and view the application over VNC by installing Xvfb, fluxbox, and x11vnc but unfortunately it doesn't seem especially stable and I'm running into other issues such as getting podman to install (even after manually installing within the container I still get errors about "/" not being a shared mount with its own rabbit hole of issues). I don't have a great option for an alternative dev environment right now. Once that changes I'll hopefully be able to actually contribute. I appreciate all the work you are doing. Making it easier for anyone to run a node is an awesome goal!

**Comment by jgresham** [comment]
Thanks for trying! I will keep this use case in mind for the future. I may even need to use a remote setup from time to time and if so I'll try to make a guide.

**Comment by keyneom** [comment]
No worries, initially I thought you should be able to run an electron app in a browser and not have issues but in retrospect that obviously isn't true. So my setup was unlikely to succeed from the start.
