### ISSUE TITLE
Type: L1/ExecutionClient Node Status: error starting

### ISSUE THREAD

**Issue by Aheesh** [NiceNode/nice-node#392]
Problem description
-

For NiceNode developers
-
{
  "platform": "linux",
  "platformRelease": "6.2.0-35-generic",
  "arch": "x64",
  "totalMemory": 33532297216,
  "niceNodeVersion": "1.0.0-alpha"
}

**Comment by jgresham** [comment]
As discussed, I've removed the outdated snap from the store.  `.deb` package should be used for installing NiceNode on Ubuntu. Thank you for reporting!
