### ISSUE TITLE
Add `/privacy` and `/terms` routes to nidenode.xyz website

### ISSUE THREAD

**Issue by jgresham** [NiceNode/nice-node#393]
## Feature details

We are finalizing the documents, but please enhance the website to allow for separate routes to both `/privacy` and `/terms`. I can then put the contents on those web pages.

- [ ] 2 small links at the bottom of nicenode.xyz
- [ ] The same header as the home page without the links in the middle

**Comment by corn-potage** [comment]
Basic structure built out:
https://github.com/NiceNode/nice-node-website/tree/feat/terms

Would it be okay if we kept the links at the top? It might make it easy for users to go back to the content they want to see on the main page.

**Comment by jgresham** [comment]
> Would it be okay if we kept the links in the header? It might make it easy for users to go back to the content they want to see on the main page.

sure, sounds good!
