### ISSUE TITLE
Migration of Storybook notation from CSF2 to CSF3

### ISSUE THREAD

**Issue by kamegoro** [NiceNode/nice-node#404]
## Feature details

Starting with Storybook v7, CSF3 notation is the recommended format, and the transition is necessary to account for the fact that CSF2 will no longer be available.

https://storybook.js.org/blog/storybook-csf3-is-here/

**Comment by jgresham** [comment]
Thanks! The csf3 `Play functions for scripted interactions` feature looks nice
