### ISSUE TITLE
Windows multiple nodes does not work. Nodes overwrite or fail without an error message

### ISSUE THREAD

**Issue by ConnorBP** [NiceNode/nice-node#431]
## Problem details

When you try to add more than one ethereum node to nice-node, it breaks in multiple ways;

node1: Nethermind + Lodestar

One issue type:
When you add a second node, on a different network, but with the same validator and consensus clients it disables the clients on the first node and then overwrites them with the second nodes clients. The first node then ceases to function.

What should happen: It should make a separate instance of each client for this network and run them on a new port and container.

Another issue:
When you try to add a second ethereum node for a different network with a different consensus and validator such as reth and nimbus, the clients fail to start entirely and do not mention any reason or log anything.

What should happen: The node should either create successfully along side the existing nodes, or prompt you with a reason why exactly it failed.

RAM: 64 GB ddr5
Storage 1700 GB free high speed NVME
cpu: 16 thread ryzen 7700x

**Comment by jgresham** [comment]
The ports are conflicting and the second node will crash if it cannot connect to the default port. If you would like a temporary work around, you can open the client settings and change the ports manually.

We don't yet handle ports well with multiple nodes. We are aware of this issue and will hopefully get to it in the next month or so! We want to implement a solution which will work well across all node types. Thank you for reporting this.
cc @corn-potage

**Comment by ConnorBP** [comment]
> The ports are conflicting and the second node will crash if it cannot connect to the default port. If you would like a temporary work around, you can open the client settings and change the ports manually.
> 
> We don't yet handle ports well with multiple nodes. We are aware of this issue and will hopefully get to it in the next month or so! We want to implement a solution which will work well across all node types. Thank you for reporting this. cc @corn-potage

Thanks for the workaround. This should solve the error when node type is different. Will there also be a fix for selecting the same node type causing it to overwrite the first nodes containers?

**Comment by jgresham** [comment]
By overwriting other nodes, do you mean overwriting their data? All nodes have separate data directories and therefore should not overwrite each other.

There is a known bug that reth does not save data when using it on a testnet.

**Comment by corn-potage** [comment]
Hey @ConnorBP, do you have some logs or screenshots so that we can see what you're seeing?

The initial port numbers to run the nodes can be changed like Johns has said, but the ports are also hardcoded for retrieving stats like peers, sync status, etc on the node package and node screens, so even if the defaults are changed in the node settings screen, the stats shown on the node screen might not work as expected.

I'll be taking a look at this to fix the first and second issue, but would be curious to see if there are additional issues happening.

**Comment by ConnorBP** [comment]
> By overwriting other nodes, do you mean overwriting their data? All nodes have separate data directories and therefore should not overwrite each other.
> 
> There is a known bug, with NiceNode & reth's config, that reth does not save data when using it on a testnet.

As in when you start a new Nethermind instance, the existing one gets shut down and the new one takes its place but under the new node. Therefor breaking the first node.

**Comment by jgresham** [comment]
Ok I understand. There is a simple naming conflict on the containers. We can fix this easily. To be clear, this would allow a user could run two nethermind nodes

**Comment by ConnorBP** [comment]
> Ok I understand. There is a simple naming conflict on the containers. We can fix this easily. To be clear, this would allow a user could run two nethermind nodes

Exactly

**Comment by jgresham** [comment]
Closing as #546 better describes the root problem now
