### ISSUE TITLE
New config settings don't show up unless node is deleted

### ISSUE THREAD

**Issue by corn-potage** [NiceNode/nice-node#46]
## Problem details

Current Behavior:
When we add new config settings in the node settings JSON, the new settings aren't displayed in the settings page. If I delete the node without deleting the node chain data, and re-add the node, the new setting shows up.

Expected behavior (?):
When a user starts the app after an app update, and opens settings for a node, new config settings should display.

Environment: Ubuntu

**Comment by jgresham** [comment]
Yup, there is no "Updates for Node Specifications" yet. The workaround is deleting the node (keep the node data storage), then re-adding the node. This does delete the node settings :(

I have some ideas on how to implement updates for node specs.

**Comment by jgresham** [comment]
temp/semi-fix in
