### ISSUE TITLE
Add checkbox to enable/configure RPC server

### ISSUE THREAD

**Issue by fubuloubu** [NiceNode/nice-node#488]
## Feature details

Not sure if the RPC server is configured by default, but if not it would be nice to have that option, to toggle on or off

If on, also allow configuring the port to expose if a custom one is desired

**Comment by jgresham** [comment]
You can! It should be available for every client. If it is missing, then I will fix that! 

Is the "flow" to get to this not intuitive? Could it be somewhere else in the app?
<img width="1225" alt="Screenshot 2024-03-13 at 8 54 00 PM" src="https://github.com/NiceNode/nice-node/assets/3721291/2d179e8f-0d91-4fc7-b162-20178aeb6388">

**Comment by fubuloubu** [comment]
> Is the "flow" to get to this not intuitive? Could it be somewhere else in the app? <img alt="Screenshot 2024-03-13 at 8 54 

Once I learned that this is hidden behind settings gear icon, it made sense

But yes, it's not quite intuitive from the first glance. Perhaps if `Config` were right next to the gear icon button it would be clearer
