### ISSUE TITLE
HELP Title Mistype: "Uninstall Podamn"

### ISSUE THREAD

**Issue by 0xJonHoldsCrypto** [NiceNode/nice-node#489]
Problem description
-

In the Help Menu there is an option to Uninstall Podman that is misspelled. 

For NiceNode developers
-
{
  "platform": "win32",
  "platformRelease": "10.0.22621",
  "arch": "x64",
  "totalMemory": 34221105152,
  "niceNodeVersion": "4.7.7-alpha"
}

**Comment by jgresham** [comment]
Thanks @0xJonHoldsCrypto!

Fixed https://github.com/NiceNode/nice-node/pull/513/commits/f44ce5d7ae96f9536fc7ac6aaeb3a79b2c0526fe
