### ISSUE TITLE
display of syncing appears mismatched with status of clients

### ISSUE THREAD

**Issue by NPRobins** [NiceNode/nice-node#491]
Problem description
-

First, great initiative and super interface! Thanks! 

I'm not sure the 'syncing' message boxes reflect the actual status of the clients. For example, my execution client is indicated as 'syncing' in the main screen, however looking at more details, it is 'synchronised'.  It's a small thing. 

For NiceNode developers
-
{
  "platform": "linux",
  "platformRelease": "6.5.0-15-generic",
  "arch": "x64",
  "totalMemory": 67305422848,
  "niceNodeVersion": "4.7.7-alpha"
}

**Comment by jgresham** [comment]
@NPRobins Thank you for reporting this. We just did a lot of work cleaning up the status of the clients at the client level and at the overall "ethereum node" level. Please let me know if you still see a discrepancy.

You were previously on NiceNode v4. There was a one time manual upgrade for v6 of NiceNode. Automatic updates work again for v6+ 

https://nicenode.xyz/#download
