### ISSUE TITLE
4.9.0-alpha not running on Fedora

### ISSUE THREAD

**Issue by fubuloubu** [NiceNode/nice-node#510]
## Problem details

On Fedora 39, after updating from 4.8.0-alpha I cannot launch the AppImage anymore, it gives me an error "Cannot mount AppImage, please check your FUSE setup" as an OS popup when I try to launch it 

There is a link to https://github.com/AppImage/AppImageKit/wiki/FUSE, I tried to find instructions there for Fedora but did not see anything I could use to solve my problem (`fuse-libs` is installed)

**Comment by fubuloubu** [comment]
Further UX feedback: would be really nice to have a selection box on what version(s) I can install, so I can decide how and when to upgrade (or downgrade) my node version

**Comment by jgresham** [comment]
> Further UX feedback: would be really nice to have a selection box on what version(s) I can install, so I can decide how and when to upgrade (or downgrade) my node version

Noted. Thanks.

As for Fedora 40 issue, If you don't mind trying to use the `.rpm` build, that should work best with Fedora. I too really liked AppImage, as installing software on various Linux distros is still so fragmented, but the official AppImage project is not active. The last release was +3 years ago, so at some point I wonder if things will start to break on its end.

**Comment by jgresham** [comment]
@fubuloubu you can manually set the version now. this is the "container version" https://github.com/NiceNode/nice-node/releases/tag/v4.10.0-alpha

**Comment by jgresham** [comment]
@fubuloubu I just updated NiceNode AppImage on Fedora from 4.X to 5.X? I had an "app not responding" popup (not sure if this was due to another app or my machine) but after clicking "wait", the update worked and I was prompted with App Image Kit's "Integrate and run" popup.

**Comment by fubuloubu** [comment]
Thanks! I had been away for a bit, but going yo update nice node and resync my reth node on beta today
