### ISSUE TITLE
Use non-conflicting ports for default on new node creation

### ISSUE THREAD

**Issue by fubuloubu** [NiceNode/nice-node#546]
## Feature details

I'm wanted to add a second node for Sepolia alongside my Mainnet node, but all the defaults when setting up are in conflict with the previous node definition so that I have to go change them all manually or else I get a startup error from the conflicts

It would be nice to auto-calculate free ports to use when setting up a new node that might share the same ports with another so I don't have to worry about this

**Comment by jgresham** [comment]
@fubuloubu this is now released in v6.1.0! You shouldn't need to, but may need to remove existing nodes for automatic non-conflicting port assignment to work for new nodes. Please let me know if you're able to test it out!
