### ISSUE TITLE
Errors with syncing Besu Client

### ISSUE THREAD

**Issue by qwert123677** [NiceNode/nice-node#668]
Problem description
-

Hello, I get this error while syncing the besu client Error: no container with name or ID "b0ba2ca39ade........." found: no such container
And sometimes the max peer count command that doesn't work 
Unknown option: '--Xp2p-peer-lower-bound=25'
For NiceNode developers Unknown option: '--Xp2p-peer-lower-bound=25'
-

  Platform:  win32
  PlatformRelease:  10.0.22631
  Distro:  Microsoft Windows 11 Home
  Release:  10.0.22631
  Arch:  x64
  TotalMemory:  33393766400
  PodmanVersion:  5.2.1
  NiceNodeVersion:  6.4.0-alpha

**Comment by jgresham** [comment]
@qwert123677 Thank you for reporting this! I just pushed a fix for this. You just need to Stop Besu, Check for Updates, and Install the update to fix this.

<img width="750" alt="Screenshot 2024-10-02 at 12 08 11 PM" src="https://github.com/user-attachments/assets/033ca717-100c-4a7b-ba46-a20217c26c78">
